name: Check if new build is needed
on: [push]
jobs:
  Check remote repo for new commits
    runs-on: ubuntu-latest
    steps:
      - name: Use GitHub API to poll commits
        run: |
          curl -sL "https://api.github.com/repos/$REMOTE_REPOSITORY/commits?sha=$REMOTE_BRANCH&per_page=1" | jq -r '[.[]][0]' > commit.json
        env:
          REMOTE_REPOSITORY: robimarko/openwrt
          REMOTE_BRANCH: IPQ807x-5.10-backports
      - name: Calculate days since last commit
        run: |
          date="$(jq -r '.commit.author.date' commit.json)"
          timestamp=$(date --utc -d "$date" +%s)
          days=$(( ( $(date --utc +%s) - $timestamp ) / 86400 ))
          echo "Days since last commit: $days"
      - name: Save as workflow variable
        run: |
          echo "COMMIT_DAYS=$days" >> $GITHUB_ENV
