name: Check if new build is needed
on: [push]
jobs:
  check:
    name: Check remote repo for new commits
    runs-on: ubuntu-latest
    steps:
      - name: Use GitHub API to poll commits
        run: |
          curl -sL "https://api.github.com/repos/$REMOTE_REPOSITORY/commits?sha=$REMOTE_BRANCH&per_page=1" | jq -r '[.[]][0]' > commit.json
        env:
          REMOTE_REPOSITORY: robimarko/openwrt
          REMOTE_BRANCH: IPQ807x-5.10-backports
      - name: Calculate hours since last commit
        run: |
          date="$(jq -r '.commit.author.date' commit.json)"
          timestamp=$(date --utc -d "$date" +%s)
          hours=$(( ( $(date --utc +%s) - $timestamp ) / 3600 ))
          echo "Last commit date: $date"
          echo "Hours since last commit: $hours"
      - name: Set job output variable
        run: |
          echo "::set-output name=commit_age::$hours"
  build:
    name: Build the remote repository
    needs: check
    runs-on: ubuntu-latest
    if: ${{ needs.check.outputs.commit_age <= 48 }}
    steps:
      - name: Testing conditional
        run: echo "Build triggered with commit age of ${{ needs.check.outputs.commit_age }} hours"

